[package]
name = "rpcurl"
version = "1.0.0"
description = "🦀[ Cli Client For KRPC ]"
rust-version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
clap = { version = "4.6.1", features = ["derive","env"] }
gethostname = "1.1.0"
serde_json = "1.0.150"
tonic = "0.14.6"
# local deps
krpc.workspace = true
tokio.workspace = true


[build-dependencies]
static_vcruntime = "3.0.0"

[lints]
workspace = true
